ALTER TABLE avatars_list
    ADD COLUMN `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    COMMENT = 'List of all available avatars';

ALTER TABLE avatars
    ADD COLUMN `expires_at` TIMESTAMP NULL DEFAULT NULL COMMENT 'If null the avatar is permanent',
    ADD COLUMN `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    COMMENT = 'Assign avatars (avatars_list) to users (login)';
